### ISSUE TITLE
update branding on all our accounts

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/design#17]
To unify branding with https://ubclaunchpad.com/

* [x] https://ubclaunchpad.com/github
* [x] https://ubclaunchpad.com/facebook
* [x] https://ubclaunchpad.com/medium
* [x] https://ubclaunchpad.com/linkedin
* [x] https://ubclaunchpad.com/slack (workspace logo)
* [x] http://reddit.com/u/ubclaunchpad
* [x] our google account

Some of these you might not have access to @sandyklc - please ping here if you need anything :)

**Comment by sandyklc** [comment]
Medium: I've updated the publication logos and branding but I don't have access to the LP account that makes articles to change the logo there.

Reddit: I don't have access to this account

Linkedin: I've updated the logo, just have to update the banner.

**Comment by bobheadxi** [comment]
* Medium: I'll update that account (though I'm hoping we stop using that account completely, and instead publish under personal accounts)

* Reddit: sent you the credentials!

* Google: I'll handle this as well :)

**Comment by bobheadxi** [comment]
@sandyklc do you mind documenting something like this as well:

* in instances where we have two accounts (for example, a Launch Pad group and Launch Pad user), use the light logo for the group and the dark logo for the user. Otherwise use the dark logo

**Comment by sandyklc** [comment]
Yes, I can document that in the Figma file that I will be making! Is it possible to add your comment to the other issue?

**Comment by bobheadxi** [comment]
You can use `>` to start a quote block to quote me, like [this](https://github.com/ubclaunchpad/design/issues/22#issuecomment-643905367)

> Yes, I can document that in the Figma file that I will be making! 

Nice! I was going to say we should add a handbook section too (`/handbook/design/branding.md`) for documentation regarding logo usage? (best practices, where to find things, etc - including the above rule)

**Comment by sandyklc** [comment]
Yup, that would definitely be useful, I can work on that. Should it be more of a UBC Launch Pad Design System section then branding can be under it?

**Comment by bobheadxi** [comment]
that works too! I'll leave it to you do decide how best to structure the content :)

looks like that's it for the accounts, thank you! let's close this issue and discuss the handbook content / design system at https://github.com/ubclaunchpad/docs/issues/107 or https://github.com/ubclaunchpad/design/issues/22 :)
